label: 'Dodawanie języków'
tips:
  language-add-overview:
    label: 'Dodawanie języków'
    body: '<p>Ta strona stwarza możliwość dodania powszechnych języków do twojej strony.</p><p>Jeśli pożądany język nie jest dostępny, dodaj własny język.</p>'
  language-add-choose:
    label: 'Wybór języka'
    body: '<p>Wybierz język z listy lub dodaj "Własny język..." na końcu listy.</p><p>Kliknij przycisk "Dodaj język" by potwierdzić wybór.</p><p>Dodając własny język będziesz mieć możliwość wprowadzenia nazwy, kodu i kierunku w kolejnym formularzu.</p>'
  language-add-continue:
    label: Kontynuując
    body: '<p>Teraz gdy masz już ogólną wiedzę na temat funkcji "Dodaj języki" możesz:<ul><li>Dodać język</li><li>Dodać własny język</li><li><a href="[site:url]admin/config/regional/language">Wyświetlić skonfigurowane języki</a></li></ul></p>'
