label: 'Edycja języków'
tips:
  language-edit-overview:
    label: 'Edycja języków'
    body: '<p>Ta strona umożliwia edycję języka witryny, włączając w to języki własne.</p>'
  language-edit-langcode:
    label: 'Kod języka'
    body: '<p>Zmiana kodu języka nie jest możliwa, jako że system korzysta z niego aby kontrolować użycie języka.</p>'
  language-edit-label:
    label: 'Nazwa języka'
    body: '<p>Nazwa języka używana jest na całej stronie, dla wszystkich użytkowników, i zapisana jest w języku Angielskim. Nazwy wbudowanych języków mogą zostać przetłumaczone korzystając z modułu Interface Translation, a nazwy zarówno wbudowanych jak i własnych języków mogą zostać przetłumaczone z pomocą modułu Configuration Translation.</p>'
  language-edit-direction:
    label: 'Kierunek pisowni języka'
    body: '<p>Wybierz czy kierunek języka to "Z lewej do prawej" czy "Z prawej do lewej".</p><p>Pamiętaj, że nie wszystkie skórki wspierają "Z prawej do lewej" więc sprawdź czy twoja skórka wspiera ten kierunek.</p>'
  language-edit-continue:
    label: Kontynuując
    body: '<p>Teraz, gdy masz podgląd na funkcję "Edycja języka", możesz kontynuować:<ul><li>Edycję języka</li><li><a href="[site:url]admin/config/regional/language">Przegląd listy skonfigurowanych języków</a></li></ul></p>'
