module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  auditfiles: 0
  auto_entitylabel: 0
  big_pipe: 0
  block: 0
  block_class: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  computed_field: 0
  config: 0
  contextual: 0
  ctools: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  editor: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  form_options_attributes: 0
  help: 0
  hook_event_dispatcher: 0
  image: 0
  language: 0
  libraries_provider: 0
  libraries_provider_ui: 0
  link: 0
  lunr: 0
  menu_ui: 0
  minifyhtml: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rules: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  tome: 0
  tome_base: 0
  tome_static: 0
  tome_static_cron: 0
  tome_static_super_cache: 0
  tome_sync: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  twig_tweak: 0
  twig_vardumper: 0
  typed_data: 0
  update: 0
  user: 0
  views_aggregator: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_conditional: 0
  views_ui: 0
  extlink: 1
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  spectre: 0
  sm: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: pl
